# General configuration
FPS = 60

# Screen configuration
SCREEN_WIDTH = 1300
SCREEN_HEIGHT = 750
BACKGROUND_COLOR = (38, 38, 38)

# InputBox configuration
INPUT_BOX_X = 1100
INPUT_BOX_Y = 700
INPUT_BOX_WIDTH = 200
INPUT_BOX_HEIGHT = 32

# VORTAC configuration
VORTAC_POS_X = SCREEN_WIDTH // 2
VORTAC_POS_Y = SCREEN_HEIGHT // 2
VORTAC_RADIUS = 250
VORTAC_COLOR = (0, 153, 51)

# Aircraft configuration
AIRCRAFT_SIZE = 10
AIRCRAFT_HEADING_VECTOR_LENGTH = 50
AIRCRAFT_EXTENDED_HEADING_VECTOR_LENGTH = 50
MAX_NUMBER_AIRCRAFTS = 7
AIRCRAFT_TURN_RATE = 0.25

# Waypoint configuration
WAYPOINT_SIZE = 7